version: '3'

services:
  # Saleor 服务
  saleor:
    image: saleor/saleor:latest
    container_name: saleor
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/saleor
      - CHANNEL_ID=default-channel
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=your-secret-key
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

  # PostgreSQL 数据库
  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=saleor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Redis 服务
  redis:
    image: redis:6
    container_name: redis
    restart: always

volumes:
  postgres_data:
